version: '3'
services:
    node:
        image: "node:stretch"
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=production
        volumes:
            - ./:/home/node/app
        expose:
            - "8001"
        command: "npm start"